/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dnslv (https://sketchfab.com/deny.s.trevisan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/alien-planet-bbb2e0eeb0b34247b8a70655c780fad5
Title: Alien Planet
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { a } from '@react-spring/three';
import alienPlanetScene from '../assets/3D/alien_planet.glb';

const AlienPlanet = (props) => {
    const alienRef = useRef();
    const { nodes, materials } = useGLTF(alienPlanetScene);

    return (
        <a.group ref={alienRef} {...props}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.Planet}
            position={[-0.045, 55, 0.066]}
            scale={[20,20,20]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.Clouds}
            position={[-0.045, 55, 0.066]}
            scale={[21,21,21]}
          />
        </a.group>
    )
}

export default AlienPlanet;