/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jacobs Development (https://sketchfab.com/Jacobs_Development)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-planet-earth-7b1dc4f802a54a6297e7a46888a85f77
Title: Low Poly Planet Earth
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { a } from '@react-spring/three';
import earthScene from '../assets/3D/planet_earth.glb';

const Earth = (props) => {
  const earthRef = useRef();
  const { nodes, materials } = useGLTF(earthScene);

  return (
    <a.group ref={earthRef} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_Planet_0.geometry}
        material={materials.Planet}
        position={[-0.045, -25, 0.066]}
        scale={[20,20,20]}
      />
    </a.group>
  )
}

export default Earth;