/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: NonDescript Grey Building (https://sketchfab.com/ndgb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toy-rocket-5d5c24e688db4ae3ba48885a5b9ceb23
Title: Toy Rocket
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from '@react-spring/three';

import rocketScene from '../assets/3D/toy_rocket.glb';

const Rocket = (props) => {
  const rocketRef = useRef();
  const { nodes, materials } = useGLTF("/toy_rocket.glb");

  return (
    <a.group ref = {rocketRef} {...props}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </a.group>
  );
}

//useGLTF.preload("/toy_rocket.glb");

export default Rocket;